sonar.projectKey=netlord2022_masar-center
sonar.organization=netlord2022
sonar.projectName=masar-center
sonar.sources=.
sonar.exclusions=node_modules/**,.nuxt/**,.output/**,dist/**,.netlify/**
sonar.typescript.tsconfigPath=tsconfig.json